sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_intall:
  - openssl aes-256-cbc -K $encrypted_dbf94599ab50_key -iv $encrypted_dbf94599ab50_iv -in multi-k8s-276215-4ce38107576c.json.enc -out multi-k8s-276215-4ce38107576c.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - glcoud config set project multi-k8s-276215
  - gcloud config set compute/zone asia-northeast1-a
  - gcloud container cluseters get-credentials umdey-multi-cluster
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_USERNAME" --password
  - docker build -t shoheihosaka/udemy-multi-k8s-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shoheihosaka/udemy-multi-k8s-test npm test

depliy:
  provider: script
  script: bash ./deploy.sh
    on:
      branch: master